trigger:
- main

pool:
  name: mac-mini-x86_64


stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build / FirstJob
    - bash: echo $(PipelineLevelVariable)

  - job: SecondJob
    steps:
    - bash: echo Build / SecondJob


- stage: DevDeploy
  dependsOn: Build
  variables:
    environment: DevDeploy
  jobs:
  - job: FirstJob
    steps:
    - bash: echo $(environment) / FirstJob

- stage: QADeploy
  dependsOn: Build
  variables:
    environment: QADeploy
  jobs:
  - job: FirstJob
    steps:
    - bash: echo $(environment) / FirstJob


- stage: ProdDeploy
  dependsOn:
  - DevDeploy
  - QADeploy
  variables:
    environment: ProdDeploy
  jobs:
  - job: FirstJob
    steps:
    - bash: echo $(environment) / FirstJob