trigger:
- main

pool:
  name: mac-mini-x86_64

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build Docker Image and Publish Files
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'emilesherrott-docker-hub'
        repository: 'emilesherrott/currency-exchange-devops'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.yaml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifests'
        publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy Image to K8S
  jobs:
  - job: Deploy
    displayName: Deploy Docker Image
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download Artifacts'
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        itemPattern: '**/*.yaml'
        targetPath: '$(System.ArtifactsDirectory)'

    - task: KubernetesManifest@1
      displayName: 'Deploy to K8S'
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'azure-kubernetes-connection'
        namespace: 'default'
        manifests: '$(System.ArtifactsDirectory)/configuration/kubernetes/deployment.yaml'
        containers: 'emilesherrott/currency-exchange-devops:$(tag)'